### ISSUE TITLE
Document `allowNone` option and make it work for multiple globs

### ISSUE THREAD

**Issue by searls** [broccolijs/broccoli-concat#31]
Right now if `allowNone` is true, the first `inputFiles` element that doesn't have any glob matches will cease processing. Ideally, `allowNone` should be accepted by the multiGlob helper method (see https://github.com/broccolijs/broccoli-kitchen-sink-helpers/issues/19 ) , but this could be worked around by rejecting `inputFiles` for which `glob.sync` has no matches.

**Comment by alanhogan** [comment]
@rlivsey @searls Was this ever added to mainline broccoli-concat?

**Comment by searls** [comment]
Not to my knowledge

**Comment by alanhogan** [comment]
I felt bad for not checking after I asked this, and it turns out it's in master & the stable release. 

(Th network page on GH did not seem to indicate that, but the commits page does)

I could still be wrong though :D

That said, allowNone works for me on stable broccoli-concat :) so if that was you, thanks!

Alan
